services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: social_media
      POSTGRES_PASSWORD: social_media
      POSTGRES_DB: social_media_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: arshdevrajput@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '8080:80'
    restart: unless-stopped

  backend:
    build: ./
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  default:
    external:
      name: shared-network
